name: Build ImeState DLL

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5


    - name: Setup MSVC x64
      shell: cmd
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath > vs.txt
        set /p VS_PATH=<vs.txt
        call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64


 - name: Build x64 DLL
  shell: cmd
  run: |
    call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath > vs.txt
    set /p VS_PATH=<vs.txt
    call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64

    cl /LD /O2 /EHsc ImeState.cpp ole32.lib oleaut32.lib imm32.lib user32.lib


    - name: Check DLL Architecture
      shell: cmd
      run: |
        dumpbin /headers ImeState.dll | findstr machine


    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: ImeStateDLL-x64
        path: ImeState.dll
