name: Build ImeState DLL


on:
  workflow_dispatch:


jobs:

  build:

    runs-on: windows-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4



    - name: Setup MSVC
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"



    - name: Build DLL
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cl /LD /O2 ImeState.cpp ole32.lib oleaut32.lib



    - name: Upload DLL
      uses: actions/upload-artifact@v4

      with:
        name: ImeStateDLL
        path:
          ImeState.dll
